type: local
executors:
  - label: local_htex
    max_workers: null  # null -> auto: min(cpu_count, 8) // 2
    cores_per_worker: 1
    worker_init: |
      export MPLBACKEND=Agg
      export JAX_DEFAULT_PRNG_IMPL=threefry2x32
retries: 1
run_dir: parsl_runinfo
